### ISSUE TITLE
I want to use this in my project. I have an ionCube license.

### ISSUE THREAD

**Issue by BeycanDeveloper** [MuriloChianfa/ioncube-encoder-action#1]
Hello, I want to use this in my project. I have an ionCube Windows Desktop license. However, since I thought I could do this with github workflows instead of doing it manually every time, I started researching and came across your repo. Can you help me with this? What do I need to use this action in my project? Also, how do we make configurations such as ionCube version selection, PHP version selection and files to be encrypted?

**Comment by BeycanDeveloper** [comment]
I just tested and: Unable to resolve action murilochianfa/ioncube-encode-action, repository not found

**Comment by MuriloChianfa** [comment]
> I just tested and: Unable to resolve action murilochianfa/ioncube-encode-action, repository not found

Sorry for the wrong typo, but now its correct, now uses:

MuriloChianfa/ioncube-encoder-action@v1.0.0

**Comment by BeycanDeveloper** [comment]
I'll test it after lunch.

By the way, how does it do this encryption? Are you using ionCube CI for this yourself?

I also saw how to specify parameters, namely ionCube and PHP versions.

There is another issue I'm curious about. Currently, when I create a release in my worklow, I also create a zip file and add it to the release. Is it possible to do this with your action package? So, first the PHP files I have chosen will be encrypted, then they will be made into a zip without touching the normal repo and added to the release. Likewise, this zip file will be sent to our own APIs.

**Comment by MuriloChianfa** [comment]
> Hello, I want to use this in my project. I have an ionCube Windows Desktop license. However, since I thought I could do this with github workflows instead of doing it manually every time, I started researching and came across your repo. Can you help me with this? What do I need to use this action in my project? Also, how do we make configurations such as ionCube version selection, PHP version selection and files to be encrypted?

You can read the **Inputs** section for all parameters to set in your pipeline, ou directly here https://github.com/MuriloChianfa/ioncube-encoder-action/blob/98cfa104d0cdb7d167c7a67967e8109a7bd7d01a/action.yml#L5

For now, you can only use the license running the pipeline on a self-hosted server or in the trial version, as I am still writing and testing the temporary activation of the license.

**Comment by MuriloChianfa** [comment]
> I'll test it after lunch.
> 
> By the way, how does it do this encryption? Are you using ionCube CI for this yourself?
> 
> I also saw how to specify parameters, namely ionCube and PHP versions.
> 
> There is another issue I'm curious about. Currently, when I create a release in my worklow, I also create a zip file and add it to the release. Is it possible to do this with your action package? So, first the PHP files I have chosen will be encrypted, then they will be made into a zip without touching the normal repo and added to the release. Likewise, this zip file will be sent to our own APIs.

Yes, im testing with IonCube CI version.

And you can integrate this workflow with another actions by example actions/upload-artifact@v3 or something like this for upload the encrypted project into one version.

would be like this:
```
name: Encode with IonCube

on: [push]

jobs:
  encode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: IonCube Encode
      uses: MuriloChianfa/ioncube-encoder-action@v1.0.0
      with:
        encoder-version: 'current'
        php-target-version: '8.2'
        arch: 64
        source: 'src'
        output: 'encrypted'

    - uses: actions/upload-artifact@v3
      with:
        name: encrypted
        path: encrypted
```
