### ISSUE TITLE
Ioncube Pro is used with a CI license, right?

### ISSUE THREAD

**Issue by 0xBeycan** [MuriloChianfa/ioncube-encoder-action#41]
I don't want to encrypt manually on the desktop anymore, I automated everything and only the ioncube process is left.

By integrating this action into my workflow, I can encrypt the files I specify, right? So how will I use my license? Will the encrypted files be temporary (test encryption) or permanent?

**Comment by MuriloChianfa** [comment]
You can use your active Ioncube license by setting up the IONCUBE_DOWNLOAD_URL secret inside the secrets section of your repository.

The download URL is provided by Ioncube in their licenses dashboard, so when you setup the provided download URL for your current active license, the package can download it and activate your license before the encryption process start and deactivate when all the process is completed.

Doing this, all the encrypted files will be valid forever or for the valid period your entered, using your license without any problems.

I had tested only using the Cerberus CI version, but I imagine that doesn't have any problems if you want to use another version.

**Comment by BeycanDeveloper** [comment]
@MuriloChianfa thank you so much

**Comment by BeycanDeveloper** [comment]
@MuriloChianfa How can I encrypt only spesific files? And copy other files only.

**Comment by MuriloChianfa** [comment]
@BeycanDeveloper you need to specify which specific files you want to encrypt and which specific files you want to just copy, directly into the workflow, something like this:
```
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: IonCube Encode Project
        uses: MuriloChianfa/ioncube-encoder-action@v2.1.1
        env:
          IONCUBE_DOWNLOAD_URL: ${{ secrets.IONCUBE_DOWNLOAD_URL }}
        with:
          trial: false
          source: 'folder/my-*-files.php'
          output: 'output_folder/'
          copy: 'folder/globbing-of-files-to-copy.php'
          encrypt: '*.blade.php'
          passphrase: ${{ secrets.IONCUBE_PASSPHRASE }}
          binary: true
          optimize: 'max'
          no-doc-comments: true
          allow-reflection-all: true
          without-loader-check: true
```

To use two different version, you need to specify it with one more instruction, e. g. "php-target-version":

```
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: IonCube Encode Project
        uses: MuriloChianfa/ioncube-encoder-action@v2.1.1
        env:
          IONCUBE_DOWNLOAD_URL: ${{ secrets.IONCUBE_DOWNLOAD_URL }}
        with:
          trial: false
          source: 'folder/my-*-files.php'
          output: 'output_folder/'
          copy: 'folder/globbing-of-files-to-copy.php'
          encrypt: '*.blade.php'
          passphrase: ${{ secrets.IONCUBE_PASSPHRASE }}
          binary: true
          optimize: 'max'
          no-doc-comments: true
          allow-reflection-all: true
          without-loader-check: true
          php-target-version: '8.2'
          
      - name: IonCube Encode Project with another version
        uses: MuriloChianfa/ioncube-encoder-action@v2.1.1
        env:
          IONCUBE_DOWNLOAD_URL: ${{ secrets.IONCUBE_DOWNLOAD_URL }}
        with:
          trial: false
          source: 'other_folder/other-*-files.php'
          output: 'other_output_folder/'
          copy: 'other_folder/globbing-of-files-to-copy.php'
          encrypt: '*.blade.php'
          passphrase: ${{ secrets.IONCUBE_PASSPHRASE }}
          binary: true
          optimize: 'max'
          no-doc-comments: true
          allow-reflection-all: true
          without-loader-check: true
          php-target-version: '7.4'
```
